<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUzsniv3\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUzsniv3/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerUzsniv3.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerUzsniv3\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerUzsniv3\appProdProjectContainer(array(
    'container.build_hash' => 'Uzsniv3',
    'container.build_id' => '630bd2bc',
    'container.build_time' => 1537624088,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerUzsniv3');
